# Permalinks
#
permalink:           /:title

# Setup
title:               "jrheard's blog"
#tagline:             'A Jekyll theme'
description:         "My name's JR Heard. I think pure functions are the greatest. I live in Portland with my cat Frank."
url:                 http://blog.jrheard.com
baseurl:             ''
paginate:            40

# Custom vars
version:             1.0.0

paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
