# Permalinks
#
permalink:           /:title

# Setup
title:               "jrheard's blog"
url:                 http://blog.jrheard.com

baseurl:             ''
paginate:            40

# Custom vars
version:             1.0.0

paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
