# Permalinks
#
permalink:           pretty

# Setup
title:               'jrheard'
#tagline:             'A Jekyll theme'
description:         "My name's <a href='http://jrheard.com'>JR Heard</a>. I think pure functions are the greatest. I live in Portland with my cat Frank."
url:                 http://blog.jrheard.com
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0

paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
